name: Docker

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: docker build --no-cache -t distance .

      - name: Unit Tests
        run: docker run cargo test
